/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '1002139' at '16. 9. 27 오후 5:42' with Gradle 3.1
 *
 * @author 1002139, @date 16. 9. 27 오후 5:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
